name: Basic CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]

env:
  HUSKY: 0

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: Type Checking
        run: |
          pnpm install --frozen-lockfile
          pnpm ci-type-check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: Linting
        run: |
          pnpm install --frozen-lockfile
          pnpm ci-lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: Unit Testing
        run: |
          pnpm install --frozen-lockfile
          pnpm ci-test
